-- Exercise Bank - Insert Script
-- Run this on your Railway MySQL database

INSERT INTO exercise (name, muscle_group, created_at, updated_at) VALUES
('belt squat', 'LEGS', NOW(), NOW()),
('crunch machine', 'ABDOS', NOW(), NOW()),
('curl haltères alternés (coude sur banc)', 'BICEPS', NOW(), NOW()),
('curl haltères alternés debout', 'BICEPS', NOW(), NOW()),
('curl poulie', 'BICEPS', NOW(), NOW()),
('curl pupitre (technogym)', 'BICEPS', NOW(), NOW()),
('Dévelope militaire (techno)', 'EPAULES', NOW(), NOW()),
('développé couché (hammer)', 'PEC', NOW(), NOW()),
('développé couché haltères', 'PEC', NOW(), NOW()),
('développé couché incliné haltères', 'PEC', NOW(), NOW()),
('développé couché incliné machine guidée', 'PEC', NOW(), NOW()),
('développé incliné (hammer)', 'PEC', NOW(), NOW()),
('dips', 'PEC', NOW(), NOW()),
('développé militaire barre debout', 'EPAULES', NOW(), NOW()),
('développé militaire haltères', 'EPAULES', NOW(), NOW()),
('développé militaire (hammer)', 'EPAULES', NOW(), NOW()),
('développé militaire (technogym)', 'EPAULES', NOW(), NOW()),
('dips machine (pure strength)', 'TRICEPS', NOW(), NOW()),
('dips triceps (technogym)', 'TRICEPS', NOW(), NOW()),
('extension triceps poulie haute', 'TRICEPS', NOW(), NOW()),
('écarté pecs technogym', 'PEC', NOW(), NOW()),
('élévation frontale poulie', 'EPAULES', NOW(), NOW()),
('élévation latérale (hammer)', 'EPAULES', NOW(), NOW()),
('élévation latérale poulie complète (hammer)', 'EPAULES', NOW(), NOW()),
('élévation latérale poulies', 'EPAULES', NOW(), NOW()),
('glutes harm raise', 'ISCHIO', NOW(), NOW()),
('hack squat', 'LEGS', NOW(), NOW()),
('leg curl', 'ISCHIO', NOW(), NOW()),
('leg extension', 'QUAD', NOW(), NOW()),
('magyc triceps', 'TRICEPS', NOW(), NOW()),
('mollets assis', 'MOLLET', NOW(), NOW()),
('mollets debout', 'MOLLET', NOW(), NOW()),
('mollets jambes tendus', 'MOLLET', NOW(), NOW()),
('relevé de genoux', 'ABDOS', NOW(), NOW()),
('extension dos poulie', 'DOS', NOW(), NOW()),
('rowing', 'DOS', NOW(), NOW()),
('tirage horizontal', 'DOS', NOW(), NOW()),
('tirage vertical hammer (trapèze)', 'DOS', NOW(), NOW()),
('Tirage vertical hammer unilatéral', 'DOS', NOW(), NOW()),
('tirage vertical poulie', 'DOS', NOW(), NOW()),
('traction', 'DOS', NOW(), NOW()),
('vis a vis haut de pecs', 'PEC', NOW(), NOW()),
('fentes smith''s machine', 'LEGS', NOW(), NOW()),
('presse a cuisse', 'LEGS', NOW(), NOW()),
('iso latéral leg press (hammer)', 'LEGS', NOW(), NOW()),
('développé décliné haltères', 'LEGS', NOW(), NOW()),
('rowing bucheron', 'DOS', NOW(), NOW()),
('tirage horizontal unilatral (technogym)', 'DOS', NOW(), NOW()),
('hip trust (hammer)', 'LEGS', NOW(), NOW()),
('développé couché prise sérrée', 'TRICEPS', NOW(), NOW()),
('adducteurs (machine)', 'LEGS', NOW(), NOW()),
('abducteurs (machine)', 'LEGS', NOW(), NOW()),
('fentes bulgare', 'LEGS', NOW(), NOW()),
('extension hanche', 'LEGS', NOW(), NOW()),
('soulevé de terre jambes tendus', 'LEGS', NOW(), NOW()),
('tirage horizontal pure strengh', 'DOS', NOW(), NOW()),
('élévation latérale panatta', 'EPAULES', NOW(), NOW()),
('extension triceps poulie basse', 'TRICEPS', NOW(), NOW()),
('crunch poulie', 'ABDOS', NOW(), NOW()),
('pendulum squat', 'LEGS', NOW(), NOW())
ON DUPLICATE KEY UPDATE updated_at = NOW();
